[package]
name = "http-redirector"
version = "0.2.0"
edition = "2018"

[lib]
name = "http_redirector"

[dependencies]
regex = "1.5"
# below dependencies are bin only
structopt = "0.3"
tokio = { version = "1.11", features = ["full"] }
hyper = { version = "0.14", features = ["server"] }
reqwest = { version = "0.11.4", default-features = false, features = ["rustls-tls"] }
