[package]
name = "http-redirector"
version = "0.1.0"
edition = "2018"

[lib]
name = "http_redirector"

[dependencies]
regex = "1.5.4"
# below dependencies are bin only
structopt = "0.3.22"
reqwest = { version = "0.11.4", features = ["blocking"] }
