[package]
name = "http-redirector"
version = "0.1.2"
edition = "2018"

[lib]
name = "http_redirector"

[dependencies]
regex = "1.5"
# below dependencies are bin only
structopt = "0.3"
ureq = "2.1"
tiny_http = { version = "0.8", features = ["default"] }
